blueprint:
  name: binary_sensor_summary
  description: Creates a sensor that summarizes binary sensor states, indicating who are on
  domain: template
  source_url: https://github.com/thiagodnf/hass-blueprints/tree/main/template/binary_sensor_summary.yaml
  author: Thiago Ferreira
  homeassistant:
    min_version: 2024.6.0
  input:
    label:
      name: Label
      description: Used to group all binary sensor-related entities
      default: door
      selector:
        text:
    icon_on:
      name: Icon On
      description: Choose an icon
      default: mdi:door-open
      selector:
        icon: {}
    icon_off:
      name: Icon Off
      description: Choose an icon
      default: mdi:door-closed
      selector:
        icon: {}
variables:
  label: !input label
  icon_on: !input icon_on
  icon_off: !input icon_off
sensor:
  icon: >-
    {% if (states(this.entity_id) | int) > 0 %}
      icon_on
    {% else %}
      icon_off
    {% endif %}
  state_class: measurement
  attributes:
    entities_on: >-
      {{ label_entities(label)  
          | expand
          | selectattr('state', 'eq', 'on')
          | map(attribute='name') 
          | list }}
    status: >-
      {% set count = states(this.entity_id) | int %}
      {{ 'All Closed' if count == 0 else count ~ ' Open' }}
  state: >-
    {{ (state_attr(this.entity_id, 'entities_on') or []) | count }}
