blueprint:
  name: summary_for_binary_sensors
  description: Creates a binary sensor summarizing the status of binary entities with a given label and device class
  domain: template
  input:
    label:
      name: Label
      description: Label used to relate entities (e.g., "door", "window", etc.)
      default: door
      selector:
        text:
    device_class:
      name: Device Class
      description: Device class assigned to the generated binary sensor (e.g., "door", "window", etc.)
      default: door
      selector:
        text:
variables:
  label: !input label
binary_sensor:
  device_class: !input device_class
  state: >-
    {{ (state_attr(this.entity_id, 'count') or 0 | int) > 0 }}
  attributes:
    count: >-
      {% set entity_ids = label_entities(label)  %}
      {{ entity_ids  
          | expand 
          | selectattr('state', 'eq', 'on') 
          | list 
          | count }}
    status: >-
      {% set count = (state_attr(this.entity_id, 'count') or 0 | int) %}
      {{ 'All Closed' if count == 0 else count ~ ' open' }}