blueprint:
  name: window_summary
  description: Creates a binary sensor that summarizes window status, indicating how many windows are open
  domain: template
  source_url: https://github.com/thiagodnf/hass-blueprints/tree/main/template/window_summary.yaml
  author: Thiago Ferreira
  homeassistant:
    min_version: 2024.6.0
  input:
    label:
      name: Label
      description: Used to group all window-related entities
      default: door
      selector:
        text:
variables:
  label: !input label
binary_sensor:
  device_class: window
  attributes:
    open_entities: >-
      {{ label_entities(label)  
          | expand
          | selectattr('state', 'eq', 'on')
          | map(attribute='name') 
          | list }}
    count: >-
      {{ state_attr(this.entity_id, 'open_entities') or [] | count }}
    status: >-
      {% set count = (state_attr(this.entity_id, 'count') or 0 | int) %}
      {{ 'All Closed' if count == 0 else count ~ ' open' }}
  state: >-
    {{ (state_attr(this.entity_id, 'count') or 0 | int) > 0 }}