blueprint:
  name: Light Brightness Transition
  description: Given Brightness Transition for Lights that does not support it
  source_url: https://github.com/thiagodnf/hass-blueprints/blob/main/blueprints/automation/light_brightness_transition.yaml.yaml
  domain: automation
  author: Thiago Ferreira
  input:
    target_lights:
      name: Lights
      description: The lights you want to control
      selector:
        target:
          entity:
            domain: light
    target_brightness:
      name: Target Brightness
      description: Set the brightness target used in the loop
      default: 100
      selector:
        number:
          min: 0
          max: 100
    trigger_time:
      name: Trigger Time
      description: Time to run this automation
      default: "22:00:00"
      selector:
        time:
    transition_time:
      name: Transition Time
      description: Time to turn the lights on
      default: 0
      selector:
        number:
          min: 0
          max: 100000
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  platform: time
  at: !input trigger_time

variables:
  target_brightness: !input target_brightness
  transition_time: !input transition_time
  step_percentage: "{{ target_brightness / transition_time  }}"
  
action:
 
  - repeat:
      sequence:
        - action: light.turn_on
          metadata: {}
          data:
            brightness_step_pct: "{{ step_percentage }}"
          target:
            entity_id: !input target_lights
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
      until:
        - condition: state
          target:
            entity_id: !input target_lights
          attribute: brightness
          state: "{{ target_brightness }}"

